### ISSUE TITLE
PHP 5.2 compatibility 

### ISSUE THREAD

**Issue by darylldoyle** [darylldoyle/svg-sanitizer#1]
Currently wont work on PHP 5.2 due to namespacing. Not sure what the pros/cons of dropping namespacing to support 5.2 could be.

**Comment by oparoz** [comment]
Please don't :) Even if some people still use 5.2, the oldest supported PHP version is 5.5. It's easier to work with more recent version of PHP.

**Comment by darylldoyle** [comment]
Those were my thoughts, only reason I can see for dropping to support PHP 5.2 is that WordPress still do. That said, even they have it marked as EOL so probably not worth it
