### ISSUE TITLE
Using this library with GPLv3 project

### ISSUE THREAD

**Issue by devishke-orange** [darylldoyle/svg-sanitizer#100]
Hi, I am considering using this library in our project which is licensed under GPLv3. I wanted to clarify if your library is licensed under "GPLv2 only" or "GPLv2 or later" 

According to the [FAQ](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) on GNU's site, we can use your library if it is the latter.

**Comment by darylldoyle** [comment]
Hi @devishke-orange, this is GPLv2 or later 🙂
