### ISSUE TITLE
svg attribute sanitizer does not filter out FuncIRI

### ISSUE THREAD

**Issue by majestrate** [darylldoyle/svg-sanitizer#2]
https://github.com/infinity-next/infinity-next/issues/121#issuecomment-143740026

http://www.w3.org/TR/SVG/types.html#DataTypeFuncIRI

Not sure how this could be fixed without castrating the SVG format.

**Comment by jaw-sh** [comment]
Are you sure? Commit db334584f1ac41843bf28e186b75905d90d92fa2 appears to be adding href cleansing to the unit tests.

**Comment by majestrate** [comment]
consider the following element

    <rect fill="url('http://trackingsite.tld/image.png')" x="0" y="0" width="1000" height="1000">
    </rect>

it doesn't use href

**Comment by darylldoyle** [comment]
Yep, you're right, the following:

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">
<rect fill="url('http://trackingsite.tld/image.png')" x="0" y="0" width="1000" height="1000">
</rect>
</svg>
```
Is not sanitised and comes out as:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">
<rect fill="url('http://trackingsite.tld/image.png')" x="0" y="0" width="1000" height="1000">
</rect>
</svg>
```

I will take a look at this tonight, it will probably require doing extra checks on the attributes listed [here](http://www.w3.org/TR/SVG/linking.html#processingIRI) and removing any external references.

**Comment by jaw-sh** [comment]
Thanks @darylldoyle for the prompt response.

By the way, regarding 5.2 compatibility, I'd advise against it. Namespaces are really important especially in modern frameworks. The last update to 5.2 was in January of 2011 -- anyone running that needs a head check.

**Comment by darylldoyle** [comment]
After looking into this a little further and consulting with a few others, it seems that externally referenced URIs in `fill`, `mask`, `filter` and `clip-path` actually pose no threat of XSS. The referenced files' JS never seems to get executed.

Whilst we could filter this to prevent HTTP leaks, I feel this might be a tad over the top. In the end, we already strip a huge number of elements/properties to stop XSS. If the referenced files are doing no harm, is it really worth the hassle of stripping them, especially considering the overhead it'd add to the processing?

I'd love to get your thoughts on it?

**Comment by darylldoyle** [comment]
Also @jaw-sh I can't see dropping to 5.2 support. Just thought I'd put the question out there. I feel if you're using 5.2, you have bigger issues that SVG attacks.

**Comment by jaw-sh** [comment]
We were looking to use this library on an imageboard software suite, 
with the intent of allowing people to distribute their own SVGs.

While it may not pose an XSS threat, imageboard users are extremely 
concerned about their privacy. I'm either going to have to drop SVG 
support or find a way to remove remote references. To me, it'd be worth 
the processing. I wouldn't even mind it as an option, like 
`$svg->removeUrls(true)`.

**Comment by darylldoyle** [comment]
I'll take a look into adding the option to turn remote references off. Not sure how much work it'll be so I'll have to look at it over the next couple of days and let you know the outcome here when I know what's happening!

Otherwise, if you have some time, feel free to add it in a PR and I'll be happy to look over it and merge.

**Comment by darylldoyle** [comment]
You now have the ability to remove remote references by using `$sanitizer->removeRemoteReferences(true);`

Better late than never eh? Let me know how you get on with it!
