### ISSUE TITLE
A project utilising svg-sanitizer is violating your license

### ISSUE THREAD

**Issue by russelg** [darylldoyle/svg-sanitizer#20]
CraftCMS (https://github.com/craftcms/cms) is violating the GPLv2 on your project svg-sanitzer. 

https://github.com/craftcms/cms/blob/develop/LICENSE.md

**Comment by darylldoyle** [comment]
Hi @russelg,

Thanks for bringing that to my attention. This is only licenced under the GPLv2 so that it's compatible with WordPress. Other than that, I'm quite happy for others to do what they want with it :)
