### ISSUE TITLE
"HTTP error" message when uploading

### ISSUE THREAD

**Issue by richb-hanover** [darylldoyle/svg-sanitizer#22]
Using both WP 4.9.8 and 5.0.2 and Safe SVG version 1.8.1, I get the following error when dragging a SVG file into the Media window.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/1094930/50347372-56c06180-0503-11e9-883d-51a792e1247f.png">

The afflicted file is at: http://test.richb-hanover.com/downloads/monguin.svg (because I cannot upload a .svg to github(!))

What other information could I collect for diagnosing this?

**Comment by richb-hanover** [comment]
Sort-of Solved - Updated info:

* The svg file actually *had* been uploaded to wp-content/uploads/2018/12/... Apparently, the "HTTP error" message is pretty generic. 
* I added `AddType image/svg+xml .svg .svgz` to the .htaccess file, and now I can see the file in the Media Library (found the clue at https://wordpress.org/support/topic/http-error-when-uploading-images-35/#post-10908592)
* BUT... I had to de-activate the Safe SVG plugin before the Media Library would appear. If the SafeSVG plugin is activated, the spinner at the top of the Media Library window just goes 'round and 'round and the image icons never appear.

So this is pretty confusing, but I think I'm working OK now... I'm happy to provide additional info if that would help

**Comment by darylldoyle** [comment]
Hi @richb-hanover,

This repo is for the sanitisation library itself rather than the WordPress plugin. I see you've opened and closed a ticket in the WordPress support forums (sorry for not getting back to you, been away over Christmas) but I'll close this in preference of that forum!
