### ISSUE TITLE
Question: why not to use kses?

### ISSUE THREAD

**Issue by markkap** [darylldoyle/svg-sanitizer#23]
Any reason why in the context of WordPress this library do not use KSES? Is it just to keep it portable or are there any other reasons?

(very shallow inspection of the code reveals functionality with is very similar to what kses does)

**Comment by darylldoyle** [comment]
Hi @markkap, the main reason to not use KSES is that this library is standalone from WordPress and therefore can be used in other PHP projects. This enables a larger proportion of the PHP community to contribute and test the library.

There was also a discussion around KSES in the initial WordPress core ticket https://core.trac.wordpress.org/ticket/24251#comment:73.

**Comment by markkap** [comment]
Thanks
