### ISSUE TITLE
Consider attributes and tags case sensitivity

### ISSUE THREAD

**Issue by tmhpfnr** [darylldoyle/svg-sanitizer#3]
Hi! IMHO the whitelisted attributes and tags should be case sensitive, e.g. viewbox becomes viewBox.

**Comment by darylldoyle** [comment]
Sorry for the delayed response.

I've been having a look into this but I'm not 100% sure on the best way to move forward with it. I see that it's an issue but as XML should be case sensitive I'm not sure how to proceed.

My initial thought was lowercasing the whole XML string before parsing, but that's going to break stuff. We could potentially use something like [this](http://codingexplained.com/coding/php/solving-xpath-case-sensitivity-with-php) but I don't like that idea, it seems very hacky and a massive pain.

Any ideas?

**Comment by TimHoepfner** [comment]
I like the idea to keep it compatible to existing implementations. Why not just adding the missing (lower camel case) attributes/tags to the default list (like I did [here](https://github.com/TimHoepfner/svg-sanitizer/commit/728615bdc0f799197ab35fa53e3e7aef8ad1f337#diff-80c36bab8514574c0b8cc4116bf852cbR151)). In my opinion your library should support the [standardized attributes](http://www.w3.org/TR/2008/REC-SVGTiny12-20081222/attributeTable.html) and tags, everything else is customization. I can't see any reason to support upper and lower case variants for the whole XML string.

A more detailed approach are different strategies for different use cases. In my case, I need a sanitized HTML inline SVG to style the paths via CSS and remove all (XML) comments, to keep the final HTML output clean.

**Comment by darylldoyle** [comment]
That sounds fair enough to me, support the camel case tags and leave it open to customisation by other implementations.

When I get a moment, I'll add the camel case tags to the default list!
