### ISSUE TITLE
Create new release tag for xss fix

### ISSUE THREAD

**Issue by larowlan** [darylldoyle/svg-sanitizer#32]
Now that #31 has been merged, is there a chance a new tag could be created so I can update drupal/svg_sanitizer to pin composer.json to versions after the security fix.

Thanks in advance

Reference issue in drupal.org tracker https://www.drupal.org/project/svg_sanitizer/issues/3064351

Thanks again for this library!

**Comment by darylldoyle** [comment]
Apologies, I thought I'd tagged this but forgot to push it 🤦‍♂ It's now been tagged as `0.12.0`.

**Comment by larowlan** [comment]
🙌
