### ISSUE TITLE
Sanitizer removes too much of data from SVG

### ISSUE THREAD

**Issue by FreddieChopin** [darylldoyle/svg-sanitizer#6]
When the attached file is uploaded via this plugin, the arrow on the vertical axis is rotated 90degrees - instead of pointing up it points to the right.

Original:
[scheduling.zip](https://github.com/darylldoyle/svg-sanitizer/files/614469/scheduling.zip)

Sanitized:
[scheduling-sanitized.zip](https://github.com/darylldoyle/svg-sanitizer/files/614470/scheduling-sanitized.zip)

Wrong:
![screenshot from 2016-11-26 22-46-35](https://cloud.githubusercontent.com/assets/1139038/20644112/40d69b54-b42a-11e6-9449-6b92c62caffc.png)

Correct:
![screenshot from 2016-11-26 22-48-47](https://cloud.githubusercontent.com/assets/1139038/20644124/8d528c04-b42a-11e6-8afe-c6bc51bafa4d.png)

If's hard to get any useful diff, as the plugin also changes all whitespace in the file...

**Comment by FreddieChopin** [comment]
Just to be clear, I'm using sanitizer via Safe SVG plugin in wordpress.

**Comment by darylldoyle** [comment]
Thanks for the report Freddie, I've narrowed this down to the orient attribute being stripped from the arrowheads. 

I'll take a closer look at this tonight and hopefully get a fix up for you!

**Comment by darylldoyle** [comment]
7a1e99504b54698607f039b4384f626d13222aeb fixes this one. A WordPress plugin update will follow shortly!

**Comment by FreddieChopin** [comment]
Thanks, the arrow is no longer changed!
