### ISSUE TITLE
Check/Remove unused id-attributes

### ISSUE THREAD

**Issue by xerc** [darylldoyle/svg-sanitizer#67]
INPUT
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 145 45">
  <metadata id="metadata"></metadata>
  <g id="whatever">
    <path id="path123"/>
  </g>
</svg>
```
OUTPUT
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 145 45">
  <metadata></metadata>
  <g>
    <path/>
  </g>
</svg>
```

**Comment by xerc** [comment]
optional/ also remove empty TAGs; `/<([a-z]+)\s*>\s*<\/\1>\s*/i/`

**Comment by xerc** [comment]
definitely ; but this ID should be in the root line of <svg/> or <symbol/> not within the content - or?

**Comment by ohader** [comment]
There are no restrictions to which nodes and how deep down in document hierarchy `id` attributes are assigned.

**Comment by xerc** [comment]
true
