### ISSUE TITLE
Blurred "drop-shadows" removed

### ISSUE THREAD

**Issue by FreddieChopin** [darylldoyle/svg-sanitizer#7]
When uploading SVG file (via Safe SVG WordPress plugin) attributes for "blur" are removed from elements.

Original:
![screenshot from 2016-12-03 13-05-37](https://cloud.githubusercontent.com/assets/1139038/20859256/a535828e-b959-11e6-8120-198f5d7918a8.png)
[task-states.zip](https://github.com/darylldoyle/svg-sanitizer/files/628828/task-states.zip)

Sanitized:
![screenshot from 2016-12-03 13-05-13](https://cloud.githubusercontent.com/assets/1139038/20859257/ab731300-b959-11e6-8dec-c4bc28a65a82.png)
[task-states-sanitized.zip](https://github.com/darylldoyle/svg-sanitizer/files/628831/task-states-sanitized.zip)

**Comment by darylldoyle** [comment]
All SVG filters should now be allowed by default!
