### ISSUE TITLE
CDATA section is removed

### ISSUE THREAD

**Issue by jkanape** [darylldoyle/svg-sanitizer#70]
From version 15.0 CDATA nodes are removed.

Example document:
```svg
<svg>
<defs>
  <style type="text/css"><![CDATA[
        .fil0 {fill:#FF0000}
   ]]></style>
 </defs>
</svg>
```

Result from 15.0 (15.1, 15.2):
```svg
<svg>
    <defs>
      <style type="text/css"></style>
    </defs>
</svg>
```
**Suspicious node '#cdata-section'**

Result before 15.0 (14.1):
```svg
<svg>
  <defs>
    <style type="[text/css]()"><![CDATA[
        .fil0 {fill:#00994E}
   ]]></style>
  </defs>
</svg>
```

Can't find a way to add `#cdata-section` to safe nodes, as list is hardcoded
```php
$safeNodes = [
    '#text',
];
```

**Comment by zcorpan** [comment]
As I commented in https://github.com/darylldoyle/svg-sanitizer/security/advisories/GHSA-fqx8-v33p-4qcc

> So are CDATA sections always removed? That seems a bit overkill, replacing them with text nodes with the same data should be safe and not remove legitimate information.
