### ISSUE TITLE
Compatibility with PHP 8.3

### ISSUE THREAD

**Issue by marchukvitaliy** [darylldoyle/svg-sanitizer#97]
For compatibility with PHP 8.3, this library needs to be updated to require "ezyang/htmlpurifier" version 4.17.0 as PHP 8.3 support has been added there https://packagist.org/packages/ezyang/htmlpurifier#v4.17.0.

**Comment by ohader** [comment]
The dependency to `ezyang/htmlpurifier: ^4.16` did only exist in the `v0.16.0` tag of this library and was reverted in commit 3729690bc660cbdad840f7608d5bdcf32e5e3f90

However, this library lacks a proper `v0.16.1` release and tag.
